# A dictionary of supported funding platform names and their corresponding identifiers
SUPPORTED_PLATFORMS = {
    'GitHub': 'invictus-ir',
}


def get_platform_identifier(platform):
    """
    Get the identifier for the given platform.

    :param platform: The platform name.
    :return: The platform identifier if the platform is supported, None otherwise.
    """
    if platform in SUPPORTED_PLATFORMS:
        return SUPPORTED_PLATFORMS[platform]
    else:
        return None


def is_platform_supported(platform):

