# Purpose: Run the linter against the PowerShell code

name: Lint Check for PowerShell

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  powershell-lint-check:
    name: MegaLint PowerShell Check
    runs-on: ubuntu-latest
    # This condition prevents duplicate runs.
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Config File
        run: cp ${{ secrets.GITHUB_WORKSPACE }}/Testing/Linting/MegaLinter/.mega-linter-powershell.yml ${{ secrets.GITHUB_WORKSPACE }}/.mega-linter.yml
      - name: Setup PSScriptAnalyzer settings
        run: cp ${{ secrets.GITHUB_WORKSPACE }}/Testing/Linting/MegaLinter/.powershell-psscriptanalyzer.psd1 ${{ secrets.GITHUB_WORKSPACE }}/.powershell-psscriptanalyzer.psd1
      - name: Lint PowerShell
        uses: oxsecurity/megalinter@v4
        with:
          args: --flavor=dotnet
          working-directory: ${{ secrets.GITHUB_WORKSPACE }}
