name: Module Version Bump

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: "New Version number (e.g., 1.2.4)"
        required: true
        type: string

jobs:
  module-version-bump:
    runs-on: windows-latest
    env:
      NEW_VERSION_NUMBER: ${{ inputs.newVersionNumber }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch the entire repository history

      - name: Set up PowerShell Core
        uses: microsoft/setup-powershell@v1

      - name: Update Module Version in Manifest
        run: |
          $manifestPath = 'Microsoft-Extractor-Suite.psm1'
          $versionRegex = '\d+\.\d+\.\d+'
          (Get-Content -Path $manifestPath) -replace "ModuleVersion = '${{ env.NEW_VERSION_NUMBER }}'", "ModuleVersion = '$(Get-LatestModuleVersion $manifestPath)'", (Get-Content -Path $manifestPath) | Set-Content -Path $manifestPath

      - name: Update Module Version in README
        run: |
          $readmePath = 'README.md'
          $badgeRegex = "Microsoft-Extractor-Suite-v\d+\.\d+\.\d+"
          $zipRegex = "Microsoft-Extractor-Suite-v\d+-\d+-\d+\.zip"
          (Get-Content -Path $readmePath) -replace $badgeRegex, "Microsoft-Extractor-Suite-v${{ env.NEW_VERSION_NUMBER}}", (Get-Content -Path $readmePath) | Set-Content -Path $readmePath

      - name: Create PR Body
        run: |
          $prTemplatePath = '`.github\pull_request_template.md'
          $description = '<!-- Describe the "what" of your changes in detail. -->'
          $motivation = '<!-- Why is this change required? -->'
          $testing = '<!-- see how your change affects other areas of the code, etc. -->'
          $removeHeader = '# <!-- Use the title to describe PR changes in the imperative mood --> #'

          $newDescription = "- This PR was created by a GitHub Action to bump Microsoft-Extractor-Suite's module version in the manifest and the README.`n - Please fill out the rest of the template that the Action did not cover. `n"
          $newMotivation = "- Bump Microsoft-Extractor-Suite's module version to v${{ env.NEW_VERSION_NUMBER }} before the next release`n"
          $newTesting = "- A human should still check if the version bumping was successful by running Microsoft-Extractor-Suite.`n"

          $prTemplateContent = (Get-Content -Path $prTemplatePath) | ForEach-Object {
            if ($_ -match $description) { $_ -replace $description, $newDescription }
            elseif ($_ -match $motivation) { $_ -replace $motivation, $newMotivation }
            elseif ($_ -match $testing) { $_ -replace $testing, $newTesting }
            elseif ($_ -match $removeHeader) { "" }
            else { $_ + "`n" }
          }

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: main
        env:
          destination_ref: ${{ env.NEW_VERSION_NUMBER }}
          title: "Bump Microsoft-Extractor-Suite module version from v$(Get-LatestModuleVersion $manifestPath) to v${{ env.NEW_VERSION_NUMBER }}"
          body: "${{ steps.create-pr-body.outputs.body }}"
          branch: "Microsoft-Extractor-Suite-version-bump-${{ env.NEW_VERSION_NUMBER }}"
          commit_message: "Update Microsoft-Extractor-Suite version to ${{ env.NEW_VERSION_NUMBER }}"

# Function to get the latest module version from the manifest
function Get-LatestModuleVersion {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory = $true)]
    [string]$manifestPath
  )

  $content = Get-Content -Path $manifestPath
  $version = $content -match 'ModuleVersion = \'(\d+\.\d+\.\d+)\'' | ForEach-Object { $Matches[1] }
  return $version
}
