name: Module Version Bump

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: "New Version number (e.g., 1.2.4)"
        required: true
        type: string

jobs:
  module-version-bump:
    runs-on: windows-latest
    env:
      NEW_VERSION_NUMBER: ${{ inputs.newVersionNumber }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Microsoft-Extractor-Suite Version Number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #
          # Replace Microsoft-Extractor-Suite module version in the manifest.
          #
          $ManifestPath = 'Microsoft-Extractor-Suite.psm1'
          $VersionRegex = "\'\d+\.\d+\.\d+\'"
          $PreviousVersion = ''
          (Get-Content -Path $ManifestPath) | ForEach-Object {
            $ModuleVersionRegex = $_ -match "ModuleVersion = $($VersionRegex)"
            if ($ModuleVersionRegex) {
                $_ -match $VersionRegex | Out-Null
                $PreviousVersion = $matches[0] -replace "'", ""
                $_ -replace $VersionRegex, "'${env:NEW_VERSION_NUMBER}'"
            }
            else {
              $_
            }
          } | Set-Content -Path $ManifestPath

          #
          # Replace Microsoft-Extractor-Suite module version version in the README
          #
          $READMEPath = '.\README.md'
          $BadgeRegex = "Microsoft-Extractor-Suite-v\d+\.\d+\.\d+"
          $ZipRegex = "Microsoft-Extractor-Suite-v\d+\-\d+\-\d+.zip"
          $ZipVerReplace = "Microsoft-Extractor-Suite-v${env:NEW_VERSION_NUMBER}" -replace '\.', '-'
          $ZipVerReplace = $ZipVerReplace + '.zip'
          (Get-Content -Path $READMEPath) | ForEach-Object {
            $BadgeVerMatch = $_ -match $BadgeRegex
            $ZipVerMatch = $_ -match $ZipRegex
            if ($BadgeVerMatch) {
              $_ -replace $BadgeRegex, "Microsoft-Extractor-Suite-v${env:NEW_VERSION_NUMBER}"
            }
            elseif ($ZipVerMatch) {
              $_ -replace $ZipRegex, $ZipVerReplace
            }
            else {
              $_
            }
          } | Set-Content -Path $READMEPath

          #
          # Create the PR body
          #
          $PRTemplatePath = '.\.github\pull_request_template.md'

          $Description = '<!-- Describe the "what" of your changes in detail. -->'
          $Motivation = '<!-- Why is this change required\? -->'
          $Testing = '<!-- see how your change affects other areas of the code, etc. -->'
          $RemoveHeader = '# <!-- Use the title to describe PR changes in the imperative mood --> #'

          $NewDescription = "- This PR was create by a GitHub Action to bump Microsoft-Extractor-Suite's module version in the manifest and the README.`n - Please fill out the rest of the template that the Action did not cover. `n"
          $NewMotivation = "- Bump Microsoft-Extractor-Suite's module version to v${env:NEW_VERSION_NUMBER} before the next release`n"
          $NewTesting = "- A human should still check if the version bumping was successful by running Microsoft-Extractor-Suite.`n"

          $PRTemplateContent = (Get-Content -Path $PRTemplatePath) | ForEach-Object {
            $DescriptionRegex = $_ -match $Description
            $MotivationRegex = $_ -match $Motivation
            $TestingRegex = $_ -match $Testing
            $RemoveHeaderRegex = $_ -match $RemoveHeader # removes unneeded new line
            if ($DescriptionRegex) {
                  $_ -replace $Description, $NewDescription
            }
            elseif ($MotivationRegex) {
                  $_ -replace $Motivation, $NewMotivation
            }
            elseif ($TestingRegex) {
                $_ -replace $Testing, $NewTesting
            }
            elseif ($RemoveHeaderRegex) {
              $_ -replace $RemoveHeader, ""
            }
            else {
              $_ + "`n"
            }
          }

          # Create the PR
          $Microsoft_Extractor_Suite_VersionBumpBranch = "Microsoft-Extractor-Suite-version-bump-${env:NEW_VERSION_NUMBER}"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b $Microsoft_Extractor_Suite_VersionBumpBranch
          git add .
          git commit -m "Update Microsoft-Extractor-Suite version to ${env:NEW_VERSION_NUMBER}"
          git push origin $Microsoft_Extractor_Suite_BumpBranch
          gh pr create -B main -H $Microsoft_Extractor_Suite__VersionBumpBranch --title "Bump Microsoft-Extractor-Suite module version from v$($PreviousVersion) to v${env:NEW_VERSION_NUMBER}" --body "${PRTemplateContent}" --label "version bump"
