# Minimal makefile for Sphinx documentation

# Directories
SOURCEDIR     := source
BUILDDIR      := build

# Sphinx executable
SPHINXBUILD   ?= sphinx-build

# Optional arguments
SPHINXOPTS    ?=

# Phony targets
.PHONY: help clean html

# Default target
all: html

# Help target
help:
	@$(SPHINXBUILD) -M help $(SOURCEDIR) $(BUILDDIR) $(SPHINXOPTS)

#
